### ISSUE TITLE
Detect errors when redux store isn't setup.

### ISSUE THREAD

**Issue by nhducit** [infinitered/reactotron-redux#7]
Reproduce:
1.
https://github.com/reactotron/reactotron/blob/master/docs/plugin-redux.md
```
// ReactotronConfig.js
import { reactotronRedux } from 'reactotron-redux'


// then add it to the plugin list
Reactotron
  .configure({ name: 'React Native Demo' })
  .use(reactotronRedux()) //  <- here i am!
```
2. ignore this step
```
const store = Reactotron.createStore(rootReducer, compose(middleware))
```

Reactotron dislay error messgage:

```
Unable to resolve error. Either support CORS by changing webpack's devtool to "source-maps" or run in offline mode.
```

**Comment by rmevans9** [comment]
I don't believe this is an issue anymore as we moved around some things in the API. If you don't add the enhancer though you will just not get any data in Reactotron. I don't believe we can detect it not being setup right since the enhancer is used AFTER you use the plugin. Closing for now as I am not sure I can do anything with this.
